

/*
	AULA 04 - EXERCÍCIO :
		REDEFINIR A ESTRUTURA DO BANCO DE DADOS DE ACORDO COM O NOVO MODELO.
*/

USE MASTER -- SE DESCONECTA DO BANCO QUE SE QUER APAGAR
GO
USE PRONTUARIO
GO
	


/*=================================================================================*/
/* REMOVENDO AS CHAVES ESTRANGEIRAS */

ALTER TABLE CLINICA.PRESCRICAO
	DROP CONSTRAINT FK_MEDICAMENTO

ALTER TABLE CLINICA.CONSULTA
	DROP CONSTRAINT FK_MEDICO

ALTER TABLE CLINICA.CONSULTA
	DROP CONSTRAINT FK_PACIENTE

ALTER TABLE CLINICA.PRESCRICAO
	DROP CONSTRAINT FK_CONSULTA

GO



/*=================================================================================*/
/* TABELA MEDICAMENTO */

--DELETE FROM CLINICA.MEDICAMENTO
TRUNCATE TABLE CLINICA.MEDICAMENTO

GO
SP_RENAME 'CLINICA.MEDICAMENTO.MDCODIGO', 'CODIGO'
GO
SP_RENAME 'CLINICA.MEDICAMENTO.MDNOME', 'NOME'
GO

/* ALTERAR NOME PARA SER NOT NULL
-- https://social.msdn.microsoft.com/Forums/pt-BR/7a3cbf97-9f6b-4023-9ece-3fffbe1cd8d1/mudar-campo-de-int-null-para-int-not-null?forum=520
*/
ALTER TABLE CLINICA.MEDICAMENTO
	ALTER COLUMN NOME VARCHAR(100) NOT NULL

ALTER TABLE CLINICA.MEDICAMENTO
	ADD DTFABRICACAO DATE NOT NULL

/* CRIAR UM ENUM
-- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c7abe3c1-cd48-4ddf-9ce2-b28d0ffb25f6/enum-in-sql-server?forum=transactsql
*/
ALTER TABLE CLINICA.MEDICAMENTO
	ADD TIPO VARCHAR(50) NOT NULL CHECK (TIPO IN('CAPSULAS', 'COMPRIMIDO'))

ALTER TABLE CLINICA.MEDICAMENTO
	ADD QUANTIDADE INT NOT NULL

GO	



/*=================================================================================*/
/* TABELA PRESCRICAO */

--DELETE FROM CLINICA.PRESCRICAO
TRUNCATE TABLE CLINICA.PRESCRICAO

GO
SP_RENAME 'CLINICA.PRESCRICAO', 'POSOLOGIA'
GO
SP_RENAME 'CLINICA.POSOLOGIA.CONCODIGO', 'CODCONSULTA'
GO
SP_RENAME 'CLINICA.POSOLOGIA.MDCODIGO', 'CODMEDICAMENTO'
GO
SP_RENAME 'CLINICA.POSOLOGIA.POSOLOGIA', 'PRESCRICAO'
GO


ALTER TABLE CLINICA.POSOLOGIA
	ALTER COLUMN PRESCRICAO VARCHAR(200) NOT NULL

GO	



/*=================================================================================*/
/* TABELA MEDICO */

--DELETE FROM CLINICA.MEDICO
TRUNCATE TABLE CLINICA.MEDICO

GO
SP_RENAME 'CLINICA.MEDICO.MEDCODIGO', 'CODIGO'
GO
SP_RENAME 'CLINICA.MEDICO.MEDNOME', 'NOME'
GO

ALTER TABLE CLINICA.MEDICO
	ALTER COLUMN NOME VARCHAR(100) NOT NULL

ALTER TABLE CLINICA.MEDICO
	ADD DTNASCIMENTO DATE NOT NULL

GO	



/*=================================================================================*/
/* TABELA PACIENTE */

--DELETE FROM CLINICA.PACIENTE
TRUNCATE TABLE CLINICA.PACIENTE

GO
SP_RENAME 'CLINICA.PACIENTE.PACCODIGO', 'CODIGO'
GO
SP_RENAME 'CLINICA.PACIENTE.PACNOME', 'NOME'
GO

ALTER TABLE CLINICA.PACIENTE
	ALTER COLUMN NOME VARCHAR(100) NOT NULL

ALTER TABLE CLINICA.PACIENTE
	ADD DTNASCIMENTO DATE NOT NULL
	
GO



/*=================================================================================*/
/* TABELA CONSULTA */

--DELETE FROM CLINICA.CONSULTA
TRUNCATE TABLE CLINICA.CONSULTA

GO
SP_RENAME 'CLINICA.CONSULTA.CONCODIGO', 'CODIGO'
GO
SP_RENAME 'CLINICA.CONSULTA.DATA', 'DTCONSULTA'
GO
SP_RENAME 'CLINICA.CONSULTA.MEDCODIGO', 'CODMEDICO'
GO
SP_RENAME 'CLINICA.CONSULTA.PACCODIGO', 'CODPACIENTE'
GO

ALTER TABLE CLINICA.CONSULTA
	ADD SALA VARCHAR(100) NOT NULL
	
GO



/*=================================================================================*/
/* RECRIANDO AS CHAVES ESTRANGEIRAS */

ALTER TABLE CLINICA.POSOLOGIA
	ADD 
		CONSTRAINT FK_MEDICAMENTO
		FOREIGN KEY (CODMEDICAMENTO)
		REFERENCES CLINICA.MEDICAMENTO (CODIGO)
	

ALTER TABLE CLINICA.CONSULTA
	ADD
		CONSTRAINT FK_MEDICO
		FOREIGN KEY (CODMEDICO)
		REFERENCES CLINICA.MEDICO (CODIGO)


ALTER TABLE CLINICA.CONSULTA
	ADD
		CONSTRAINT FK_PACIENTE
		FOREIGN KEY (CODPACIENTE)
		REFERENCES CLINICA.PACIENTE (CODIGO)
	

ALTER TABLE CLINICA.POSOLOGIA
	ADD
		CONSTRAINT FK_CONSULTA
		FOREIGN KEY (CODCONSULTA)
		REFERENCES CLINICA.CONSULTA (CODIGO)

GO	



SELECT * FROM PRONTUARIO.CLINICA.MEDICO
SELECT * FROM PRONTUARIO.CLINICA.PACIENTE
SELECT * FROM PRONTUARIO.CLINICA.MEDICAMENTO
SELECT * FROM PRONTUARIO.CLINICA.POSOLOGIA
SELECT * FROM PRONTUARIO.CLINICA.CONSULTA

