
/*
ROTEIRO:
1 - ADICIONAR COLUNAS	--
2 - RENOMEAR OBJETOS 	-- TABELAS, COLUNAS, INDICES ETC . . .
3 - DELETAR REGISTROS	--
4 - DROP CHAVES			--
5 - RECRIAR CHAVES		--
6 - DROP COLUNA			--
7 - INSERIR REGISTROS	--
*/

USE MASTER -- SE DESCONECTA DO BANCO QUE SE QUER APAGAR
USE PRONTUARIO
GO

/*=================================================================================*/
-- 1 - ADICIONAR COLUNAS
		-- A TABELA MEDICAMENTOS TEM APENAS DOIS CAMPOS (MDCODIGO, NOME)
		-- AGORA SERÁ ADICIONADO UM TERCEIRO CHAMADO "QUANTIDADE"

ALTER TABLE PRONTUARIO.CLINICA.MEDICAMENTO
	--ADD QUANTIDADE INT NOT NULL
	/*	NESTE CASO, COMO A TABELA JÁ ESTÁ PREENCHIDA NÃO É POSSÍVEL CRIAR UMA NOVA COLUNA
		QUE SEJA NÃO NULO, POIS ELE NÃO SABERIA QUE VALOR COLOCAR NESTE CAMPO JÁ QUE ELE É DE PREENCHIMENTO OBRIGATÓRIO.
	*/
	ADD QUANTIDADE INT NULL



/*=================================================================================*/
-- 2 RENOMEAR OBJETOS
		-- RENOMEAR A COLUNA ADICONADA NO ITEM ANTERIOR (QUANTIDADE)
		-- ESTE COMANDO PODE SER UTILIZADO PARA RENOMEAR TABELAS, COLUNAS, INDICES ETC . . .

SP_RENAME 'CLINICA.MEDICAMENTO.QUANTIDADE', 'QTD'



/*=================================================================================*/
-- 3 DELETAR REGISTROS
		-- CASO ALGUM REGISTRO DA TABELA SIRVA COMO CHAVE ESTRANGEIRA PARA OUTRA TABELA, NÃO SERÁ POSSÍVEL
		-- DAR UM DELETE OU TRUNCATE NA TABELA POIS ISSO PODERIA GERAR INCONSISTÊNCIA.

DELETE FROM CLINICA.PRESCRICAO
TRUNCATE TABLE CLINICA.PRESCRICAO

/*
	TRUNCATE TABLE CLINICA.MEDICAMENTO
*/
	-- TRUNCATE APAGA E RECONSTROI A TABELA MEDICAMENTO O QUE FAZ COM QUE TODOS OS REGISTROS SEJAM APAGADOS E
	-- O VALOR DOS CAMPOS AUTO INCREMENTAVEIS SÃO RESETADOS.
	-- POR ESTE MOTIVO NÃO É POSSÍVEL DAR UM TRUNCATE NA TABELA MEDICAMENTO, POIS ELE TERIA QUE DESTRUIR A TABELA E
	-- COMO EXISTE A TABELA PRESCICAO QUE UTILIZA A TABELA MEDICAMENTO COMO CHAVE ESTRANGEIRA, NÃO SERÁ POSSÍVEL
	-- DESTRUIR A TABELA PARA RECRIÁ-LA.
	-- O CÓDIGO ABAIXO REALIZA TODAS AS ALTERAÇÕES PARA SE REALIZAR O TRUNCATE NA TABELA MEDICAMENTO :



/*=================================================================================*/
--	4 - DROP CHAVES
--	5 - RECRIAR CHAVES

/*
	ALTER TABLE CLINICA.PRESCRICAO
		DROP CONSTRAINT FK_MEDICAMENTO

	TRUNCATE TABLE CLINICA.MEDICAMENTO

	ALTER TABLE CLINICA.PRESCRICAO
		ADD
			CONSTRAINT FK_MEDICAMENTO
			FOREIGN KEY (MDCODIGO)
			REFERENCES PRONTUARIO.CLINICA.MEDICAMENTO (MDCODIGO)
*/







